name: Deploy on QA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy_on_qa:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Create customer env file
        working-directory: ./customer
        run: |
          touch .env
          echo APP_SECRET=${{ secrets.QA_APP_SECRET }} >> .env
          echo MONGODB_URI=${{ secrets.QA_CUSTOMER_DB_URL }} >> .env
          echo MSG_QUEUE_URL=${{ secrets.QA_MSG_QUEUE_URL }} >> .env
          echo EXCHANGE_NAME=DUKA >> .env
          echo PORT=8001 >> .env
          cat .env

      - name: Create products env file
        working-directory: ./products
        run: |
          touch .env
          echo APP_SECRET=${{ secrets.QA_APP_SECRET }} >> .env
          echo MONGODB_URI=${{ secrets.QA_PRODUCTS_DB_URL }} >> .env
          echo MSG_QUEUE_URL=${{ secrets.QA_MSG_QUEUE_URL }} >> .env
          echo EXCHANGE_NAME=DUKA >> .env
          echo PORT=8002 >> .env
          cat .env

          
      - name: Create shopping env file
        working-directory: ./shopping
        run: |
          touch .env
          echo APP_SECRET=${{ secrets.QA_APP_SECRET }} >> .env
          echo MONGODB_URI=${{ secrets.QA_SHOPPING_DB_URL }} >> .env
          echo MSG_QUEUE_URL=${{ secrets.QA_MSG_QUEUE_URL }} >> .env
          echo EXCHANGE_NAME=DUKA >> .env
          echo PORT=8003 >> .env
          cat .env
      

      - name: Generate deployment package
        run: |
          zip -r deploy.zip . -x '*.git'

      - name: Deploy on Elastic beanstalk QA Env
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: duka-qa-nodejs
          environment_name: Duka-qa-nodejs-env
          version_label: ${{ github.sha }}
          use_existing_version_if_available: true
          region: eu-north-1
          deployment_package: deploy.zip
     
